version: '3'

services:
  mongo:
    image: mongo:5.0.3
    container_name: partituras-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./infrastructure/volumes/mongo/:/data/db
    networks:
      - partituras-internal
networks:
  partituras-internal:
